### ISSUE TITLE
Support for Typescript .tsx?

### ISSUE THREAD

**Issue by mindplay-dk** [nippur72/RiotTS#7] opened 2015-09-08 21:24 UTC
Do you think it's possible to support [JSX](https://github.com/Microsoft/TypeScript/wiki/JSX) now that it's going to be supported by Typescript 1.6?

Having integration between React and Typescript JSX could potentially lead to the best IDE support any lightweight UI framework has ever seen :-)

At present, it would require a hack (or a custom JSX compile step) since Typescript is currently hard-wired to `React.*`, but [they are discussing options](https://github.com/Microsoft/TypeScript/issues/3788) and maybe you'd like to chime in and let them know what you think is needed to provide integration/support for other frameworks such as Riot?

**Comment by nippur72** [comment] 2015-09-09 07:40
Some time ago I tried to figure out how JSX and Riot could be mixed together, but I wasn't able to come out with a good solution, so I pushed aside the idea. 

The major obstacle is that JSX support is too specifically made for React, and even if they "generalize" it, a react-like framework has to be used.

But I might be wrong, so I will keep an eye on it. 

Of course if you have a suggestion on how to make riot work with JSX, please share here. Writing a JSX plugin should not be a problem I guess.

**Comment by mindplay-dk** [comment] 2015-09-09 18:35
At the moment, as far as I can tell, the only thing that ties this feature to React, is the fact that the generated code says e.g. `React.createElement(...)` - at the moment, you can simply declare a module with a function of that name, and you're set.

There's nothing React-specific about the way that this function works, as far as I can tell - it's expected to take an element name, attributes, and a variable number of child elements, and return any sort of model created from that.

For example, the following compiles and works, without React:

```
module React {
  export function createElement(tag : any, props ?: any, ...children : any[]) : any {
    console.log(arguments);
  }
}

var a = <div>
  {[12, 20].map(i => <span>half of {i} is {i/2}</span>)}
</div>
```

Riot has an element-model of some sort, right? It should be possible to take the input data and create whatever model is needed from that (?)

Type-checking elements is done by [adding them to the JSX namespace](https://github.com/Microsoft/TypeScript/wiki/JSX#intrinsic-elements).

I don't think there's much more to it than that. But I haven't really dug into the innards of Riot, so I don't really know how it works ;-)

**Comment by nippur72** [comment] 2015-09-10 08:07
The problem is not how to plug it to JSX. Even if it's hardcoded we could write a fake `React` class that maps to riot. 

The actual problem is that they are too different frameworks. Riot is more like Polymer than React. 

Perhaps we could use JSX transformation not for runtime, but for compile-time. E.g. the JSX could generated a .js that in turn generates a .tag template file that can be loaded by riot. 

I suggest to look if other JSX implementations will emerge (e.g. for Polymer, Angular, etc) so we can "steal" the idea.

**Comment by web3d0** [comment] 2015-10-25 09:11
I spent the afternoon trying to use JSX instead of ES6 template strings (a la srackham). JSX doesn't really offer anything extra that can't be done with ES6, including external generation of tag strings.

I did have luck with passing a Class to the riot.tag() function, so this could be a way to re-merge the template and the code into a single file. However I suspect RiotTS does a bit more connection work.

**Comment by mindplay-dk** [comment] 2015-10-25 09:33
> JSX doesn't really offer anything extra that can't be done with ES6

@web3d0 really, how about IDE and compile-time support - inspections for proper nesting and attributes/types, auto-completion, etc.? This is the main thing (nay, the only thing) I wanted out of JSX support in the first place...

**Comment by web3d0** [comment] 2015-10-25 10:55
As @nippur72 said, the problem is that the syntax inside of the tag file is Riot's own little template language. Using JSX won't fix up whether it's "variable" or "this.variable" or the Riot looping constructs, etc. So putting JSX into Riot means rewriting the templating engine rather than plugging them together.

**Comment by nippur72** [comment] 2015-11-23 17:01
As there is no clear way how to make .tsx work with riot, I'm closing this for now.

**Closed as completed by nippur72** 2015-11-23 17:01 UTC
Labels: wontfix
